### ISSUE TITLE
HERTZ algorithm based asset support?

### ISSUE THREAD

**Issue by grctest** [wackou/bts_tools#24]
HERTZ is an upcoming algorithm based asset (smartcoin/mpa) which is pegged against a to be agreed-upon backing asset and modified to oscillate between rising the price feed and decreasing it in a predictable manner, thus we create phases of buying and selling pressure constantly back and forth forever.

I'd appreciate support in your price feeds, so that more witnesses will be able to provide feeds.

Relevant links:
[Bitsharestalk](https://bitsharestalk.org/index.php/topic,24161.0.html)
[Steemit](https://steemit.com/bitshares/@cm-steem/hertz-fba-created)
[Xeroc's price feed script - hertz issue](https://github.com/xeroc/bitshares-pricefeed/issues/3)
[Haskell HERTZ price feed script - Github](https://github.com/grctest/HERTZ-Price-feed-script/)
[Openledger link](https://openledger.io/asset/HERTZ/)
[Cryptofresh](http://cryptofresh.com/a/HERTZ)

---

The python price feed script uses time/dates instead of block numbers, so perhaps there will be a difference in computed values between haskell and python? Would the time calculation just be more granular/accurate?

python pseudocode implementation? (***I don't know python***)

```
import math
import date

reference_asset_price = feeds['CNY']   // Reference asset still TBA
Time_In_Period = one month duration
amplitude = 0.5

x_value = remainder of (((date.today() - date(Asset_Genesis_Date_Timestamp))/Time_In_Period)/1.00))  // to return 0.xx

 feeds['HERTZ'] = reference_asset_price + (((reference_asset_price * amplitude)*(sin((x_value * Time_In_Period)) * ((2*math.pi)/Time_In_Period) ))))
```

**Comment by grctest** [comment]
Update: https://steemit.com/beyondbitcoin/@cm-steem/hertz-haskell-price-feed-script-update

I've created a simplified haskell script as a reference: https://github.com/grctest/HERTZ-Price-feed-script/blob/master/min_hertz.hs

**Comment by wackou** [comment]
Thanks for the suggestion, I like the idea! Not sure if it's going to be useful (don't have enough understanding of economics yet), but just the fact that we are able to try things like that on BitShares is plain awesome.
A bit busy with the launch of PeerPlays right now, but I'll give it a try soon :)

**Comment by grctest** [comment]
@wackou How has the peerplays launch gone thus far? I've still yet to claim my sharedropped PPY, but when I do I'll be upvoting your witness for sure! 👍

**Comment by grctest** [comment]
Ping! @wackou Would you consider working on this If I provided a reasonable USD bounty on the task?

Thanks, voted for your peerplays witness, keep up the great work! 👍

**Comment by grctest** [comment]
https://github.com/wackou/bts_tools/pull/34
