### ISSUE TITLE
HERO 'maintenance_collateral_ratio' difference between bts_tools & other price feed scripts

### ISSUE THREAD

**Issue by grctest** [wackou/bts_tools#33]
https://github.com/wackou/bts_tools/blob/master/bts_tools/templates/config/monitoring.yaml#L41

Listed as 200%

Yet in the following scripts by it's set to 175% : 
https://github.com/hero-global/scripts/blob/master/hero-feed.py#L33
https://github.com/xeroc/bitshares-pricefeed/blob/master/bitshares_pricefeed/examples/hero.yaml#L47

The [official HERO page on collateral](http://docs.hero.global/en/master/collateral.html) lists:

> The maintenance collateral ratio for HERO is:
> ```175%  (2017-05-01)```

**Comment by wackou** [comment]
double-checked with xeroc, he confirmed that the recommended value is 200%, his feeds and the website need to be updated
