### ISSUE TITLE
Request: New release

### ISSUE THREAD

**Issue by grctest** [wackou/bts_tools#48]
Hey @wackou,

Could you please create a new bts_tools release? The current release doesn't have some of the latest improvements (including Hertz changes).

Alternatively, instructions could include installing a downloaded clone of the repo to get the latest dev changes?

Thanks,
CM.

edit: after https://github.com/wackou/bts_tools/pull/50 though, lol.

**Comment by grctest** [comment]
Thanks 👍

**Comment by wackou** [comment]
no problem, thank you for contributing the code for the Hertz asset! Still planning to do a proper release annoucement, feed publishing has been much enhanced in the latest release
